title: "Portfólio – Jorge Simocovski"
description: "Product Discovery • Qualidade • Estratégia • Engenharia"
url: "https://jorgesmk.github.io"
baseurl: "/Jorge-Simocovski"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"

# Theme settings
plugins:
  - jekyll-include-cache

# Author information (aparece no rodapé e sidebar)
author:
  name: "Jorge Simocovski"
  avatar: /assets/images/avatar.jpg # opcional
  bio: "Profissional de Produto e Engenharia. Especialista em Qualidade, Discovery e Delivery."
  location: "Brasil"

# To enable the navigation
include:
  - _pages

# Defaults to make pages look good without esforço
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
